version: '3'
services:
  stateoftheaeapps-backend:
    image: shardlabs/ct-stateoftheaepps-backend:stable
    container_name: stateoftheaeapps-backend
    ports:
      - '2052:5000'
    networks:
      - stateoftheaeapps-network
    restart: always
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - stateoftheaeapps-backend
    restart: always
    environment:
      DOMAINS: 'api.aepps.shardlabs.io -> http://stateoftheaeapps-backend:5000'
      STAGE: 'production' # Don't use production until staging works
      FORCE_RENEW: 'true'
    networks:
      - stateoftheaeapps-network

networks:
  stateoftheaeapps-network:
